# Pivot Tables and Reshaping

Move between long and wide formats while preserving the meaning of each observation.

> 🧭 This notebook focuses on practical data work. Examples are intentionally compact and do not cover machine learning.

## Learning goals
- Build summary tables with `pivot_table` and `crosstab`.
- Understand why `pivot` requires unique index-column pairs.
- Convert wide data to long format with `melt`.
- Choose the row granularity before reshaping data.

In [1]:
import pandas as pd

sales = pd.DataFrame({
    "month": ["Jan", "Jan", "Feb", "Feb", "Mar", "Mar", "Mar"],
    "region": ["North", "South", "North", "South", "North", "South", "South"],
    "revenue": [100, 80, 120, 90, 140, 95, 20],
})
display(sales)

  month region  revenue
0   Jan  North      100
1   Jan  South       80
2   Feb  North      120
3   Feb  South       90
4   Mar  North      140
5   Mar  South       95
6   Mar  South       20

## Pivot tables aggregate duplicates
`pivot_table` can aggregate multiple records for the same region-month pair. Set `aggfunc` explicitly when the default mean is not appropriate.

In [2]:
wide = sales.pivot_table(index="month", columns="region", values="revenue", aggfunc="sum", fill_value=0)
display(wide)
print("Long-form row count:", len(sales), "Wide cells:", wide.size)

counts = pd.crosstab(sales["month"], sales["region"])
display(counts)

Long-form row count: 7 Wide cells: 6

region  North  South
month
Feb       120     90
Jan       100     80
Mar       140    115

region  North  South
month
Feb         1      1
Jan         1      1
Mar         1      2

## Pivot and melt
Use `pivot` when each `(index, columns)` pair is unique. Use `melt` to turn repeated value columns into a tidy two-column variable/value structure.

In [3]:
unique_sales = pd.DataFrame({"month": ["Jan", "Jan", "Feb", "Feb"], "region": ["North", "South", "North", "South"], "revenue": [100, 80, 120, 90]})
unique_wide = unique_sales.pivot(index="month", columns="region", values="revenue")
display(unique_wide)
long_again = unique_wide.reset_index().melt(id_vars="month", var_name="region", value_name="revenue")
display(long_again.sort_values(["month", "region"]))

region  North  South
month
Feb       120     90
Jan       100     80

  month region  revenue
0   Feb  North      120
2   Feb  South       90
1   Jan  North      100
3   Jan  South       80

## Common reshaping mistakes
- A pivot fails if keys are not unique; decide how duplicates should be aggregated.
- A missing value in a pivot is not necessarily zero. Use `fill_value=0` only when absence truly means no activity.
- After a `reset_index`, index labels become columns and should be named intentionally.

## Practice
Create a pivot table with sum of revenue by month and region, then melt it back into long format.

In [4]:
answer_wide = sales.pivot_table(index="month", columns="region", values="revenue", aggfunc="sum")
display(answer_wide)
answer_long = answer_wide.reset_index().melt(id_vars="month", var_name="region", value_name="revenue")
display(answer_long)

region  North  South
month
Feb       120     90
Jan       100     80
Mar       140    115

  month region  revenue
0   Feb  North      120
1   Jan  North      100
2   Mar  North      140
3   Feb  South       90
4   Jan  South       80
5   Mar  South      115